name: create-cp-dump-exe
run-name: ${{ github.actor }} x9000-code-plug-dumper
on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest']

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - run: pip install pyinstaller
    - run: pyinstaller research/cp_dump.py
    - uses: actions/upload-artifact@v2
      with:
        path: dist/*
