#!/usr/bin/python3
# ida2nfo <list file generated by IDA pro> <nfo file to generate>
import sys
import re

args = len(sys.argv)

if args != 3:
    print('Usage:')
    print('  ida2nfo <list file generated by IDA pro> <nfo file to generate>')
    sys.exit()

in_file = sys.argv[1]
out_file = sys.argv[2]

try:
    fp_in = open(in_file,mode='r')
    fp_out = open(out_file,mode='w')
except OSError as err:
    print(err)
    exit(code=err.errno)

while True:
    line = fp_in.readline()
    if not line:
        break;
    #m = re.search(r';',line)
    m = re.search(r'([0-9A-Fa-f]{4}).*;(.*)',line)
    if m:
        while True:
            comment=m.group(2)
            skipped=''
            if re.search(r'DATA XREF:',comment):
                skipped=comment
                break

            if re.search(r'CODE XREF:',comment):
                skipped=comment
                break

            if re.search(r'seg[0-9A-F]{3}:[0-9A-F]{4}',comment):
                skipped=comment
                break

            if re.search(r'sub_[0-9A-F]{4}',comment):
                skipped=comment
                break

            if re.search(r"'.{0,1}'",comment):
                skipped=comment
                break

            if re.search('---------------------------------------------------------------------------',comment):
                skipped=comment
                break

            if re.search('=============== S U B R O U T I N E =======================================',comment):
                skipped=comment
                break

            if re.search('File Name   :',comment):
                skipped=comment
                break

            if re.search('Format      :',comment):
                skipped=comment
                break

            if re.search('Base Address:',comment):
                skipped=comment
                break

            if re.search("end of 'seg",comment):
                skipped=comment
                break

            if re.search(r'[0-9A-F]{4} [0-9A-F]{2}.*fcb .*',m.group(0)):
                skipped=m.group(0)
                break

            #print(line,end='')
            #print(f'group(1) "{m.group(1)}"')
            #print(f'group(2) "{m.group(2)}"')
            break
        if skipped:
            #print(f'skipped "{skipped}"')
            pass
        else:
            out_line=f'comment {m.group(1)} {m.group(2)}\n'
            #print(f'writing "{out_line}"',end='')
            fp_out.write(out_line)
                
                                
        


